name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Python Generator
        run: |
          python generators/python_generator.py --dir test_py
          [ -d test_py/src ] && echo "Python test passed"
          
      - name: Test Node.js Generator
        run: |
          node generators/nodejs_generator.js test_node
          [ -d test_node/src ] && echo "Node.js test passed"
